language: rust
env:
    global:
        - secure: jS3X2wCwnJgAUnCP7MmeSFR/o7kX9MZxcLQcfWwFIFHe83qGys4Xa+csLz7y/5e7n64UYJtn8ZwIgLfCZawalOPQN3SaFrtv1AAnU47YOQhvk++9A8mmg6R/lMuObSqqQteIvL0lkaGmOWBtB81QPg3vsYWgFhdjqGE1seWUsxE=
        - LD_LIBRARY_PATH: /usr/local/lib
install:
    - sudo add-apt-repository ppa:team-xbmc/ppa -y
    - sudo apt-get update -q
    - sudo apt-get install libsdl2-dev
script:
    - cargo build -v
    - cargo test -v
    - cargo doc -v
after_success:
    - cp -R target/doc doc
    - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh
    - rm -r doc
