before_install:
  - yes | sudo add-apt-repository ppa:hansjorg/rust
  - sudo apt-get update
install:
  - sudo apt-get install rust-nightly
  - wget http://www.libsdl.org/release/SDL2-2.0.0.tar.gz
  - tar -zxvf SDL2-2.0.0.tar.gz
  - cd SDL2-2.0.0
  - ./configure && make && sudo make install
  - cd -
script:
  - make compile_demos
