language: rust
os:
    - linux
    - osx
env:
    global:
        - LD_LIBRARY_PATH: /usr/local/lib
install:
  - wget http://www.libsdl.org/release/SDL2-2.0.0.tar.gz
  - tar -zxvf SDL2-2.0.0.tar.gz
  - cd SDL2-2.0.0
  - ./configure && make && sudo make install
  - cd -
script:
  - cargo build -v
  - make compile_demo
