[package]
name = "sdl2_image"
version = "0.2.2"
authors = ["xsleonard"]
description = "SDL2_image bindings and wrappers"
license = "MIT"
repository = "https://github.com/xsleonard/rust-sdl2_image"
keywords = ["SDL2"]

[lib]
name = "sdl2_image"
path = "src/sdl2_image/lib.rs"

[dependencies]
bitflags = "0.1.1"
libc = "0.1.6"
sdl2 = "0.5"
sdl2-sys = "0.5"

[[bin]]
name = "demo"
path = "src/demo/main.rs"
