[package]

name = "sdl2_ttf"
description = "SDL2_ttf bindings for Rust"
repository = "https://github.com/andelf/rust-sdl2_ttf"
version = "0.0.3"
license = "MIT"
readme = "README.md"
authors = [ "ShuYu Wang <andelf@gmail.com>" ]
keywords = ["SDL", "windowing", "graphics", "font"]

[lib]

name = "sdl2_ttf"
path = "src/sdl2_ttf/lib.rs"

[dependencies]

bitflags = "0.1"
sdl2 = "0.0.25"
sdl2-sys = "0.0.25"

[[bin]]

name = "demo"
path = "src/demo/main.rs"
