[package]

name    = "sdl2"
description = "SDL2 bindings for Rust"
repository = "https://github.com/AngryLawyer/rust-sdl2"
documentation = "http://angrylawyer.github.io/rust-sdl2/sdl2/"
version = "0.10.0"
license = "MIT"
authors = [ "Tony Aldridge <tony@angry-lawyer.com>" ]
keywords = ["SDL", "windowing", "graphics"]

[lib]

name       = "sdl2"
path       = "src/sdl2/lib.rs"

[dependencies]
num = "0.1"
bitflags = "0.3.2"
libc = "0.2"
rand = "0.3"

[dependencies.sdl2-sys]

path = "sdl2-sys"
version = "0.7.0"

[features]

default = []
use-pkgconfig = [ "sdl2-sys/use-pkgconfig" ]
