[package]

name    = "sdl2"
description = "SDL2 bindings for Rust"
repository = "https://github.com/AngryLawyer/rust-sdl2"
version = "0.0.35"
license = "MIT"
authors = [ "Tony Aldridge <tony@angry-lawyer.com>" ]
keywords = ["SDL", "windowing", "graphics"]

[lib]

name       = "sdl2"
path       = "src/sdl2/lib.rs"

[dependencies]
bitflags = "0.1"
libc = "*"
rand = "*"

[dependencies.sdl2-sys]

path = "sdl2-sys"
version = "0.0.33"

[features]

default = []
use-pkgconfig = [ "sdl2-sys/use-pkgconfig" ]
