[package]

name    = "sdl2"
version = "0.0.1"
authors = [ "Tony Aldridge<zaragopha@hotmail.com>" ]
build   = "make src/sdl2/generated/keycode.rs src/sdl2/generated/scancode.rs"

[[lib]]

name       = "sdl2"
path       = "src/sdl2/lib.rs"

[[bin]]

name = "demo"
path = "src/demo/main.rs"

[dev-dependencies.codegen]

path = "src/codegen"
