[package]
name = "sdl2_mixer"
description = "SDL2_mixer bindings for Rust"
repository = "https://github.com/andelf/rust-sdl2_mixer"
version = "0.2.1"
license = "MIT"
authors = ["ShuYu Wang <andelf@gmail.com>"]
keywords = ["SDL", "windowing", "graphics", "music", "sound"]

[lib]
name = "sdl2_mixer"
path = "src/sdl2_mixer/lib.rs"

[dependencies]
bitflags = "0.1"
sdl2 = "0.2.1"
sdl2-sys = "0.2.1"
libc = "0.1.6"

# [dependencies.sdl2]
# git = "https://github.com/AngryLawyer/rust-sdl2"

# [dependencies.sdl2-sys]
# git = "https://github.com/AngryLawyer/rust-sdl2"

[[bin]]
name = "demo"
path = "src/demo/main.rs"
