[package]

name = "sdl2-sys"
description = "Raw SDL2 bindings for Rust, used internally rust-sdl2"
repository = "https://github.com/AngryLawyer/rust-sdl2"
version = "0.0.19"
authors = ["Tony Aldridge <tony@angry-lawyer.com>"]
license = "MIT"
links = "SDL2"
build = "build.rs"

[lib]
name = "sdl2-sys"
path = "src/lib.rs"

[build-dependencies]
pkg-config = "0.1.6"

[features]

default = []
use-pkgconfig = []
